### PR TITLE
[#4][Chore] Configure Staging deployment

### LINKED ISSUE #4: [Chore] Configure Staging deployment
## Why

In order to ensure any change in `develop` is reflected in the **staging** environment.

Use `netlify` by following [these instructions](https://create-react-app.dev/docs/deployment#netlify).

## Who Benefits?

Developers.

### PR DESCRIPTION
**Pull request by malparty**
- #4 

## What happened 👀

- [x] Configure Netlify to auto-deploy `develop` branch on any change (mostly PR merging)
- [x] Configure Netlify to support client-side routing
- [x] Configure Netlify to enable PR preview ❤️

## Insight 📝

I will follow Netlify naming: 
- The `production` release is available at [react-survey.netlify.com](https://react-survey.netlify.app)
- The `staging` release will refer to the PR previews which URL is provided by the Netlify bot

> When starting to consume the API, I will configure the Netlify PROD to consume the production release of the API while the PR previews will consume the staging release of the API.

### Manual Deployment are passing

[react-survey.netlify.com](https://react-survey.netlify.app)

image

### When a new PR is created (even DRAFT), a Preview Deployment is triggered

image

The preview deployment URL is available in the PR discussion, thanks to Netlify Bot:

image

The preview is working well!

image

### CODE REVIEW

**Review by rafayet-monon — APPROVED** [review]
So it's configured from the netlify dashboard right? You gave netlify your project access and netlify does automation on PR merge?

**Review by rafayet-monon — COMMENTED** [review]
Do you think maybe it could be better if the deployment was done using github actions rather than controlling from the netlify?

**Comment by malparty** [comment]
> Do you think maybe it could be better if the deployment was done using github actions rather than controlling from the netlify?

@rafayet-monon I think it really depends on what we need. For the IC, we do not need more than staging/prod and Netlify provides already more (1 preview per PR = multiple staging somehow -- valid for Releases too).
So in this situation, I believe it is perfectly fine. In case the need evolves, switching from Netlify trigger to GitHub Action triggers is pretty easy (2x boxes to uncheck in Netlify, then add the [Netlify GitHub Actions](https://github.com/marketplace/actions/netlify-actions) whereever needed).

Note that the Netlify GitHub Action also enables to deploy as previews :)

**Review by carryall — COMMENTED** [review]
@malparty So do you planned to adjust the deployment configured again after finished all the test configuration? Because I'm not sure that if we configured the deployment from Netlify then can we trigger it only after the test on CI pipeline is passed 💭

**Comment by malparty** [comment]
> after the test on CI pip

Good question @carryall :) 

- As there is 1 different preview environment per Pull Request, we do not need to prevent the deployment when testing (as this won't affect team members testing another PR — as they will be on another deployed version).
  --> So no problem on pushing.

- Last case is when merging a PR (aka deploying the production environment). Today the config is based so that Prod = develop branch. Later, after we have some releases, I will change the configuration so that the production is `main`.
As GitHub is configured to prevent merge if the tests are not passing, then Netflix cannot be in a situation where a merge to develop (or main) has failing tests. 
  --> So I guess it's all good :)

**Review by carryall — APPROVED** [review]
All good then 👍🏼

**Pull request merged**
